#!/usr/bin/env python

import rospy

import os
import sys
import time

from gazebo_msgs.srv import SetModelState, SetModelStateRequest

pose_list = [
    [-0.1, -0.5, 0.75, 0.0, 0.0, 0.0, 1.0],
    [0.5, -0.5, 0.75, 0.0, 0.0, 0.0, 1.0],
    [0.5, 0.0, 0.75, 0.0, 0.0, 0.0, 1.0]
]

index_pose=0

def request_tag_pose(pose):
    rqst = SetModelStateRequest()
    rqst.model_state.model_name = "tag_01"
    rqt_pose = rqst.model_state.pose
    rqt_pose.position.x = pose[0]
    rqt_pose.position.y = pose[1]
    rqt_pose.position.z = pose[2]
    rqt_pose.orientation.x = pose[3]
    rqt_pose.orientation.y = pose[4]
    rqt_pose.orientation.z = pose[5]
    rqt_pose.orientation.w = pose[5]
    rqst.model_state.reference_frame = "world"
    
    srv = rospy.ServiceProxy('/gazebo/set_model_state', SetModelState)
    srv.wait_for_service()
    srv.call(rqst)

def trigger_cb(event):
    global index_pose
    request_tag_pose(pose_list[index_pose])
    index_pose += 1
    if index_pose>=3:
        index_pose = 0


if __name__ == "__main__":
    rospy.init_node('scxml_interprefeter_simple_node')
    rospy.Timer(rospy.Duration(5), trigger_cb)
    rospy.spin()